Next/Previous buttons like in player. Enables manual autoplay.
otommod/chrome-mpris2 pull request #13
Opened 2018-09-04 17:21 UTC by CBiX

I think it makes more sense to have the previous/next-buttons if and only if they are active in the original player, independent of a playlist. This is particularly useful because outside of playlists you will usually have a next-button to manually skip to the recommended autoplay video.

Tested in Chrome 61.0.3163.100.

2018-09-04 18:27 UTC, otommod requested changes
* use `===` everywhere
* leave a space between the `if` and the `(`
* don't use `{}` for single statement `if`s

2018-09-04 18:28 UTC, otommod commented
I was actually thinking of doing that.  I only have some stylistic complaints.

2018-09-04 23:05 UTC, CBiX commented
There you go ;)

2018-09-05 08:31 UTC, merged

2018-09-05 08:31 UTC, otommod commented
thank you!